USE Movies;
DROP TABLE IF EXISTS fletnix_user;
CREATE TABLE fletnix_user (
    userID INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL
) ON [PRIMARY]
